services:
  serv1:
    build:
      context: .
      dockerfile: ./deployments/serv1.Dockerfile
      args:
          - GO_VERSION=1.24

    container_name: serv1
    depends_on:
          - redis
          - rabbitmq
          - postgres
    ports:
          - "8080:8080"

  postgres:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"


  redis:
    image: redis/redis-stack-server:latest 
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data 
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: my_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  redis_data:
  rabbitmq_data:

