version: '3.8'

services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  serv1:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile.serv1
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  serv2:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile.serv2
    ports:
      - "8080:8081"
    depends_on:
      - postgres
